PRODUCTION_FIELD_HELP = {
    "horas_turno": {
        "title": "Horas por turno",
        "description": "Número de horas previstas para cada turno operativo.",
        "example": "8 horas.",
        "impact": "Se usa para calcular las horas brutas disponibles del día.",
    },
    "numero_turnos": {
        "title": "Número de turnos",
        "description": "Cantidad de turnos productivos previstos para la jornada.",
        "example": "1 turno normal o 2 turnos en campaña alta.",
        "impact": "Multiplica la capacidad diaria disponible.",
    },
    "horas_descanso": {
        "title": "Horas de descanso",
        "description": "Tiempo no productivo previsto dentro de la jornada total.",
        "example": "0.5 equivale a 30 minutos.",
        "impact": "Se descuenta de las horas brutas para calcular las horas útiles.",
    },
    "tipo_campana": {
        "title": "Tipo de campaña",
        "description": "Nivel general de actividad del almacén.",
        "example": "Normal, Alta o Pico campaña.",
        "impact": "Puede servir después para ajustar rendimientos y saturaciones recomendadas.",
    },
    "tipos_volcado_activos": {
        "title": "Líneas de volcado activas",
        "description": "Indica qué líneas o formas de entrada de fruta estarán disponibles durante la jornada. No es una opción excluyente: pueden estar activas varias a la vez.",
        "example": "Compacta + Línea invierno si ambas se van a utilizar el mismo día.",
        "impact": "Estas líneas condicionan la capacidad de entrada de fruta, la continuidad de trabajo y posibles cuellos de botella. En fases posteriores se cruzarán con máquinas, rendimientos y saturación.",
    },
    "saturacion_maxima_pct": {
        "title": "Saturación máxima %",
        "description": "Porcentaje máximo recomendable de ocupación de la capacidad disponible.",
        "example": "90%.",
        "impact": "Evita planificar al 100% permanente, dejando margen para paradas, cambios y retrasos.",
    },
    "permitir_horas_extra": {
        "title": "Permitir horas extra",
        "description": "Indica si la simulación podrá considerar ampliación de jornada.",
        "example": "Activado en días de mucho pedido.",
        "impact": "Permite cubrir déficit de capacidad sin aumentar turnos.",
    },
    "permitir_segundo_turno": {
        "title": "Permitir segundo turno",
        "description": "Indica si puede proponerse un segundo turno como solución.",
        "example": "Activado en pico de campaña.",
        "impact": "Aumenta la capacidad diaria disponible, pero requiere personal y organización adicional.",
    },
    "priorizar_pedidos_reales": {
        "title": "Priorizar pedidos reales",
        "description": "Da preferencia a pedidos confirmados frente a pedidos previstos.",
        "example": "Activado por defecto.",
        "impact": "Reduce el riesgo de consumir capacidad en pedidos no firmes.",
    },
    "permitir_adelantar_produccion": {
        "title": "Permitir adelantar producción",
        "description": "Permite producir antes de la fecha límite si hay capacidad libre.",
        "example": "Adelantar pedidos de mañana cuando hoy sobra capacidad.",
        "impact": "Ayuda a suavizar picos de carga y reducir riesgo de retrasos.",
    },
    "agrupar_pedidos_compatibles": {
        "title": "Agrupar pedidos compatibles",
        "description": "Permite considerar juntos pedidos similares por confección, formato, cliente o plataforma.",
        "example": "Agrupar varias mallas de 2 kg del mismo cliente.",
        "impact": "Reduce cambios de máquina, material y etiqueta.",
    },
    "minimizar_cambios_formato": {
        "title": "Minimizar cambios de formato",
        "description": "Prioriza una planificación con menos cambios de kg, material, malla o configuración.",
        "example": "Hacer primero todas las mallas de 2 kg antes de cambiar a 1.5 kg.",
        "impact": "Mejora rendimiento real y reduce tiempos muertos.",
    },
    "kg_objetivo_dia": {
        "title": "Kg objetivo día",
        "description": "Kilos totales que se desea producir en la jornada.",
        "example": "80.000 kg.",
        "impact": "Sirve como referencia contra la capacidad estimada.",
    },
    "palets_objetivo_dia": {
        "title": "Palets objetivo día",
        "description": "Número de palets que se espera preparar durante la jornada.",
        "example": "240 palets.",
        "impact": "Ayuda a prever carga de paletizado, flejado y expedición.",
    },
    "pedidos_maximos_recomendados": {
        "title": "Pedidos máximos recomendados",
        "description": "Número máximo orientativo de pedidos que conviene gestionar en el día.",
        "example": "40 pedidos.",
        "impact": "Controla la fragmentación operativa y los cambios excesivos.",
    },
    "horas_brutas_dia": {
        "title": "Horas brutas día",
        "description": "Resultado de multiplicar horas por turno por número de turnos.",
        "example": "8 horas x 1 turno = 8 horas.",
        "impact": "Indica la capacidad horaria teórica antes de descontar descansos.",
    },
    "horas_utiles_dia": {
        "title": "Horas útiles día",
        "description": "Horas realmente disponibles tras descontar descansos.",
        "example": "8 - 0.5 = 7.5 horas.",
        "impact": "Es la base real para calcular capacidad productiva.",
    },
    "saturacion_util_objetivo": {
        "title": "Saturación útil objetivo",
        "description": "Horas útiles ajustadas por el porcentaje máximo de saturación.",
        "example": "7.5 horas x 90% = 6.75 horas.",
        "impact": "Representa la capacidad planificable recomendada sin forzar el almacén.",
    },
}
